import * as prismic from "@prismicio/client";
import { RichText } from "prismic-reactjs";


import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ page }) {
  console.log(page.data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            {RichText.asText(page.data.titulo)}
        </h1>

        <p>
          {RichText.asText(page.data.resumo)}
        </p>

        <img src={page.data.imagem.url} alt=""/>

        <div>
          <RichText render={page.data.post} />
        </div>

      </main>
    </div>
  )
}

export async function getStaticProps() {
  // API endpoint for the Prismic CMS repository.
  const endpoint = prismic.getEndpoint("testeblogff");

  // Client used to fetch CMS content.
  const client = prismic.createClient(endpoint);

  // Page document for our homepage from the CMS.
  const page = await client.getByUID("posts", "primeiro-post");

  // Pass the homepage as prop to our page.
  return {
    props: { page },
  };
}
