import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Prismic from 'prismic-reactjs'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{props.titulo}</h1>
      </main>
    </div>
  )
}

export async function getServerSideProps({ res }) {
  const client = Prismic.client('https://testeblogff.prismic.io/api/v2')
  const posts = await client.query(Prismic.Predicates.at('document.type', 'posts'))
  return {
    props: {
      posts: product.posts,
    },
  }
}
